### PR TITLE
Fix font size for rare taxa list

### PR DESCRIPTION
**Pull request by EmbrietteH**
This PR adds the previous code change done by Luke, and in addition, further changes the font size from small to footnotesize to ensure participant pdfs are a single page.

### CODE REVIEW

**Comment by mortonjt** [comment]
This is interesting.  Looks like the build took too long :/

**Comment by mortonjt** [comment]
Looking over this [post](https://github.com/travis-ci/travis-ci/issues/5201), I'd try adding `travis_wait` at the beginning of the last line in the [`.travis.yml`](https://github.com/biocore/American-Gut/blob/master/.travis.yml)

**Comment by EmbrietteH** [comment]
The build has completed successfully now (thanks @mortonjt ). @mortonjt  @squirrelo @josenavas can I get a review?

**Comment by squirrelo** [comment]
Code looks fine. Is there a before & after render screenshot?

**Comment by EmbrietteH** [comment]
Before and after shots. Before: 2 pages due to the rare taxa list being too long and pushing down the PCoA plots onto the second page. After: everything on a single page.

Note that the number of rare taxa is slightly different as the before shot was taken from results produced after rounds1-21 and the after shots was taken from results produced after rounds 1-22.

after
before

**Comment by squirrelo** [comment]
Looks good to me, :+1:

**Pull request merged**
