### PR TITLE
r1-15 data

### PR DESCRIPTION
**Pull request by wasade**
ag r1-15 data. changes to processing notebook etc will come in a different PR once they're complete

### CODE REVIEW

**Comment by wasade** [comment]
@JWDebelius @adamrp @ElDeveloper @josenavas @squirrelo @antgonza, possible for rapid review on this? its just data, so review should consist of some level of sanity check. this is one of the final pieces blocking reaching out to collaborators.

**Comment by JWDebelius** [comment]
Is there a reason AG.txt is not being updated?
Everything but the AG.txt/AG.biom pair look sane to me.

**Comment by wasade** [comment]
Good catch

**Comment by wasade** [comment]
should be good to go, if anyone is able to merge

**Pull request merged**
