### PR TITLE
Adding data dictionary

### PR DESCRIPTION
**Pull request by wasade**
Just a dump of the AG data [dictionary](https://docs.google.com/spreadsheets/d/1hUqLc4LtZiYK4ls2EJolE8oAwppzHBBdvZPGD9H4NwM/edit?usp=sharing) on Drive

### CODE REVIEW

**Comment by wasade** [comment]
@JWDebelius @adamrp @ElDeveloper, is this okay to merge?

**Comment by wasade** [comment]
@JWDebelius, okay to merge?

**Comment by JWDebelius** [comment]
Can we close this, and then open a new one with the updated data dictionary?

**Comment by wasade** [comment]
Sure

**Pull request closed without merging**
