### PR TITLE
Adds images

### PR DESCRIPTION
**Pull request by JWDebelius**
These are images that should appear in the power notebook. They somehow didn't get merged before.

### CODE REVIEW

**Comment by wasade** [comment]
@JWDebelius, can you lump in the fix for index.ipynb as well please? We really need to have index working

**Comment by JWDebelius** [comment]
@wasade, Sorry, I'm not sure what happened. I fixed the index notebook. 

I added some organization. I can take it back to the previous version, though, if that's preferred.

**Comment by wasade** [comment]
This renders, however the links are relative to your repo not biocore. Can you please fix the links?

**Comment by JWDebelius** [comment]
That may be because it's currently located in my repository. 

The markdown for each link is 

```Primary processing pipeline [Notebook](module2_v1.0.ipynb)```

so, it's relative to the current repository.

**Comment by wasade** [comment]
Oh, I see. Thanks

**Pull request merged**
