### PR TITLE
Makes alpha diveristy images PNGs

### PR DESCRIPTION
**Pull request by JWDebelius**
Because even though vector based graphics are awesome, they come with great responsibility.

Addresses #196

### CODE REVIEW

**Comment by squirrelo** [comment]
:+1:  assuming tests pass

**Comment by JWDebelius** [comment]
@EmbrietteH @mortonjt ping?

**Comment by EmbrietteH** [comment]
I've seen the outputs and I approve. @mortonjt can you give this a once over?

**Comment by JWDebelius** [comment]
@mortonjt, ping

**Pull request merged**
